### ISSUE TITLE
doesn't work with symfony3

### ISSUE THREAD

**Issue by compworkmail** [AshleyDawson/SimplePaginationBundle#1]
Hello. I have tried according to your readme file install your bundle, but it gives me an error in symfony3:

Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidDefinitionException' with message '->cannotBeEmpty() is not applicable to NumericNodeDefinition.' in /home/vaha/www/feastme.net/src/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Builder/NumericNodeDefinition.php:71 Stack trace: #0 /home/vaha/www/feastme.net/src/vendor/ashleydawson/simple-pagination-bundle/AshleyDawson/SimplePaginationBundle/DependencyInjection/Configuration.php(29): Symfony\Component\Config\Definition\Builder\NumericNodeDefinition->cannotBeEmpty() #1 /home/vaha/www/feastme.net/src/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(50): AshleyDawson\SimplePaginationBundle\DependencyInjection\Configuration->getConfigTreeBuilder() #2 /home/vaha/www/feastme.net/src/vendor/ashleydawson/simple-pagination-bundle/AshleyDawson/SimplePaginationBundle/DependencyInjection/AshleyDawsonSimplePaginationExtension.php(27): Symfony\Component\Config\Definition\Processor->processConfiguration(Objec in /home/vaha/www/feastme.net/src/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Builder/NumericNodeDefinition.php on line 71

**Comment by AdamHornik** [comment]
Hello, I had the same issue with Symfony 3. I made a fork of this bundle, where I fixed this issue. You could check here: https://github.com/nikdyvice/SimplePaginationBundle

**Comment by j0k3r** [comment]
Since https://github.com/AshleyDawson/SimplePaginationBundle/pull/2 it works fine.
